<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>FolderPeek</AssemblyName>
    <RootNamespace>FolderPeek</RootNamespace>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FolderPeek.Core\FolderPeek.Core.csproj" />
  </ItemGroup>
</Project>
