<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AssemblyName>FolderGlimpse.Tests</AssemblyName>
    <RootNamespace>FolderGlimpse.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FolderGlimpse.Core\FolderGlimpse.Core.csproj" />
  </ItemGroup>
</Project>
